/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SentimentAnalysisRouteImport } from './routes/sentiment-analysis'
import { Route as FeedbackTableRouteImport } from './routes/feedback-table'
import { Route as FeedbackAnalyticsRouteImport } from './routes/feedback-analytics'
import { Route as DoctorPerformanceRouteImport } from './routes/doctor-performance'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ComplaintsManagementRouteImport } from './routes/complaints-management'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SentimentAnalysisRoute = SentimentAnalysisRouteImport.update({
  id: '/sentiment-analysis',
  path: '/sentiment-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackTableRoute = FeedbackTableRouteImport.update({
  id: '/feedback-table',
  path: '/feedback-table',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackAnalyticsRoute = FeedbackAnalyticsRouteImport.update({
  id: '/feedback-analytics',
  path: '/feedback-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorPerformanceRoute = DoctorPerformanceRouteImport.update({
  id: '/doctor-performance',
  path: '/doctor-performance',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsManagementRoute = ComplaintsManagementRouteImport.update({
  id: '/complaints-management',
  path: '/complaints-management',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/complaints-management': typeof ComplaintsManagementRoute
  '/dashboard': typeof DashboardRoute
  '/doctor-performance': typeof DoctorPerformanceRoute
  '/feedback-analytics': typeof FeedbackAnalyticsRoute
  '/feedback-table': typeof FeedbackTableRoute
  '/sentiment-analysis': typeof SentimentAnalysisRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/complaints-management': typeof ComplaintsManagementRoute
  '/dashboard': typeof DashboardRoute
  '/doctor-performance': typeof DoctorPerformanceRoute
  '/feedback-analytics': typeof FeedbackAnalyticsRoute
  '/feedback-table': typeof FeedbackTableRoute
  '/sentiment-analysis': typeof SentimentAnalysisRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/complaints-management': typeof ComplaintsManagementRoute
  '/dashboard': typeof DashboardRoute
  '/doctor-performance': typeof DoctorPerformanceRoute
  '/feedback-analytics': typeof FeedbackAnalyticsRoute
  '/feedback-table': typeof FeedbackTableRoute
  '/sentiment-analysis': typeof SentimentAnalysisRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/complaints-management'
    | '/dashboard'
    | '/doctor-performance'
    | '/feedback-analytics'
    | '/feedback-table'
    | '/sentiment-analysis'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/complaints-management'
    | '/dashboard'
    | '/doctor-performance'
    | '/feedback-analytics'
    | '/feedback-table'
    | '/sentiment-analysis'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/complaints-management'
    | '/dashboard'
    | '/doctor-performance'
    | '/feedback-analytics'
    | '/feedback-table'
    | '/sentiment-analysis'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComplaintsManagementRoute: typeof ComplaintsManagementRoute
  DashboardRoute: typeof DashboardRoute
  DoctorPerformanceRoute: typeof DoctorPerformanceRoute
  FeedbackAnalyticsRoute: typeof FeedbackAnalyticsRoute
  FeedbackTableRoute: typeof FeedbackTableRoute
  SentimentAnalysisRoute: typeof SentimentAnalysisRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sentiment-analysis': {
      id: '/sentiment-analysis'
      path: '/sentiment-analysis'
      fullPath: '/sentiment-analysis'
      preLoaderRoute: typeof SentimentAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback-table': {
      id: '/feedback-table'
      path: '/feedback-table'
      fullPath: '/feedback-table'
      preLoaderRoute: typeof FeedbackTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback-analytics': {
      id: '/feedback-analytics'
      path: '/feedback-analytics'
      fullPath: '/feedback-analytics'
      preLoaderRoute: typeof FeedbackAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor-performance': {
      id: '/doctor-performance'
      path: '/doctor-performance'
      fullPath: '/doctor-performance'
      preLoaderRoute: typeof DoctorPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints-management': {
      id: '/complaints-management'
      path: '/complaints-management'
      fullPath: '/complaints-management'
      preLoaderRoute: typeof ComplaintsManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComplaintsManagementRoute: ComplaintsManagementRoute,
  DashboardRoute: DashboardRoute,
  DoctorPerformanceRoute: DoctorPerformanceRoute,
  FeedbackAnalyticsRoute: FeedbackAnalyticsRoute,
  FeedbackTableRoute: FeedbackTableRoute,
  SentimentAnalysisRoute: SentimentAnalysisRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
